version: "3.9"

services:
  # translator:
  #   build: .
  #   container_name: translator-api
  #   ports:
  #     - "8000:8000"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   restart: unless-stopped
  # db:
  #   image: postgres:15
  #   container_name: translator-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_DB=translator
  #     - POSTGRES_USER=translator
  #     - POSTGRES_PASSWORD=translator
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false   # disable auth for dev
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  pgdata:
  esdata: